### ISSUE TITLE
Support event.key?

### ISSUE THREAD

**Issue by felixfbecker** [nfriend/ts-keycode-enum#4]
`event.which` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which

`event.key` is supported in all browsers: 
![image](https://user-images.githubusercontent.com/10532611/41319611-505a2c8e-6e51-11e8-9249-f2a8dde96285.png)
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

but typed as `string` in TS and therefor not typesafe.
All keys without a print representation are listed here: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

it would be awesome to have them as a string enum

**Comment by nfriend** [comment]
Interesting - I had no idea `event.which` was deprecated!  (As is [ `event.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)!)

I agree that a `string` enum option would be ideal going forward.  I wonder if this would make sense as a separate module, maybe named "ts-key-enum"?

**Comment by nfriend** [comment]
I just whipped up a string enum version of this module: https://github.com/nfriend/ts-key-enum

NPM: https://www.npmjs.com/package/ts-key-enum

Can you take a look and let me know what you think?

**Comment by felixfbecker** [comment]
Wow, thanks for doing that so quickly. A new module makes lots of sense.

I would suggest though to remove all enum members that are for printable characters. There isn't really any benefit in writing `Key.a` over `'a'`, and you will never cover all characters anyway (think about non-english characters like ä, all special characters in Unicode, etc), so this just increases the bundle size of the module.

I would only include all non-printable characters like `Escape`, `ArrowLeft`, etc that are easy to mistype (is it `ArrowLeft` or `LeftArrow`?) so an enum actually provides type safety benefits.

Speaking of bundle size, could you add `files` to package.json so I don't have to download that png image?

Another thing I would look at is writing a little script to generate the enum - a simple `document.querySelectorAll('td:first-child code')` on that page gives all key values.

**Comment by nfriend** [comment]
@felixfbecker - Thanks for the suggestions, I took all of them!  Scraping the list from MDN was a great idea (see [scrapeMDNForKeys.ts](https://github.com/nfriend/ts-key-enum/blob/master/scrapeMDNForKeys.ts)) and also allowed me to pull in the descriptions for each enum value as JSDoc.  

Feel free to take a look at [ts-key-enum@2.0.0](https://github.com/nfriend/ts-key-enum) and let me know what you think.

On an unrelated note - I see that SourceGraph has an open position for a remote TypeScript dev? I might be interested :)

**Comment by felixfbecker** [comment]
Awesome, works perfectly! Will follow up via email

**Comment by nfriend** [comment]
@felixfbecker - Just put in an application :)
